### ISSUE TITLE
remove un-reviewed changes from dev branch

### ISSUE THREAD

**Issue by escalonn** [1058-Sophia-Gavrila-Forge/Forge-Backend#3]
same problem as [here](https://github.com/1058-Sophia-Gavrila-Forge/Portfolio-Frontend/pull/1#issuecomment-881743448)

_Originally posted by @escalonn in https://github.com/1058-Sophia-Gavrila-Forge/Forge-Backend/issues/1#issuecomment-881752909_

**Comment by MDarmawan** [comment]
PR went through
